# Generated by Django 4.1.4 on 2023-01-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='Closed'),
        ),
    ]
